"""director table

Revision ID: 02e0a94d3b5b
Revises: 
Create Date: 2021-01-20 13:50:31.175200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02e0a94d3b5b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('director',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_director_name'), 'director', ['name'], unique=True)
    op.create_table('episode',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_episode_title'), 'episode', ['title'], unique=True)
    op.create_table('association_director_episode',
    sa.Column('director_id', sa.Integer(), nullable=False),
    sa.Column('episode_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['director_id'], ['director.id'], ),
    sa.ForeignKeyConstraint(['episode_id'], ['episode.id'], ),
    sa.PrimaryKeyConstraint('director_id', 'episode_id')
    )
    op.create_table('viewed',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('viewed', sa.Boolean(), nullable=True),
    sa.Column('episodes', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['episodes'], ['episode.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('viewed')
    op.drop_table('association_director_episode')
    op.drop_index(op.f('ix_episode_title'), table_name='episode')
    op.drop_table('episode')
    op.drop_index(op.f('ix_director_name'), table_name='director')
    op.drop_table('director')
    # ### end Alembic commands ###
